
mindmap
    Intro
        Socialisation
            Social Media
        Startups
            Startups Graveyard
            Startups 101
        Health Wellness
            Exercise
            Diet
        Learning
            Lessons Learned
            Books
        Travel
            Visited Places
        Philosophy
            Personal
                    My Thoughts
        Finance
            Credit Card
                Axis Bank
                    Flipkart Axis Bank Credit Card
                            Miscellaneous Update
                Resources
            Investment
                Equity
                    Stocks
                            'Stocks 101 : A Guide to Stock Market Jargon'
                Cryptocurrency
                Debt
                Misc
                        Miscellaneous
                        P2P Lending
                        Foreclosure Properties
            Banking
                Icici
                        ICICI Bank
                        Miscellaneous Charges
        Entertainment
            Img
            Music
            Movies
                    Movies & Web Series
        Misc
            Operating Systems
                Linux
                        Linux/Unix 
                Windows
                Mac Os
                        Wiki How for MacOS
                        Mac OS
            Photography
        Tools
            Software Tools
            Hardware Tools
            Web Tools
        Technology
            Rf
                    RF
            Ai
                    Artificial Intelligence
