
mindmap
    Intro
        Health Wellness
            Diet
            Exercise
        Philosophy
            Personal
                    My Thoughts
        Technology
            Rf
                    RF
            Ai
                    Artificial Intelligence
        Learning
            Books
            Lessons Learned
        Explorations
            Shopping
            Dining Out
            Destinations
        Tools
            Web Tools
            Github Resources
            Multimedia
        Entertainment
            Img
            Music
            Films
        Socialisation
            Social Media
        Finance
            Banking
                Icici
                        Miscellaneous Charges
                        ICICI Bank
            Investment
                Cryptocurrency
                Equity
                    Stocks
                            'Stocks 101 : A Guide to Stock Market Jargon'
                Debt
                Misc
                        P2P Lending
                        Miscellaneous
                        Foreclosure Properties
            Credit Card
                Resources
                Axis Bank
                    Flipkart Axis Bank Credit Card
                            Miscellaneous Update
        Startups
            Startups 101
            Startups Graveyard
        Misc
            Operating Systems
                Linux
                        Linux/Unix 
                Mac Os
                        Wiki How for MacOS
                        Mac OS
                Windows
            Photography
