name: Bug Report
description: Create a report to help us improve the wiki.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Page URL
      description: If the bug is on a specific page, please provide the URL.
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we see the error?
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
