name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          git-user: suryakantamangaraj
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
